Usuarios:
    

Salas :
    'Canalobre3' : 57
    'Canalobre4' : 61
    'Canalobre5' : 59
    'Canalobre6' : 63
    'Canalobre7' : 65
    'Canalobre8' : 67
    'Canalobre9' : 69
    '1102' : 73
    '1103' : 79
    '1104' : 75
    '1105' : 77
    '1107' : 81
    '6010' : 51

Intervalos :
    Uno :
        'beginPeriod' : '08:00:00'
        'endPeriod' : '10:00:00'
    Dos :
        'beginPeriod' : '10:00:00'
        'endPeriod' : '12:00:00'
    Tres :
        'beginPeriod' : '12:00:00'
        'endPeriod' : '14:00:00'
    Cuatro :
        'beginPeriod' : '14:00:00'
        'endPeriod' : '16:00:00'
    Cinco :
        'beginPeriod' : '16:00:00'
        'endPeriod' : '18:00:00'
    Seis :
        'beginPeriod' : '18:00:00'
        'endPeriod' : '20:00:00'
